---
- name: Install nginx web-server
  import_tasks: ngx_install.yml
  become: True
  become_user: root
  tags:
    - ngx_install

- name: Configure nginx web-server
  import_tasks: ngx_configure.yml
  become: True
  become_user: root
  tags:
    - ngx_install

- name: Provision HTTPs certificates
  import_tasks: ngx_https.yml
  when: ngx_provision_https
  become: True
  become_user: root
  tags:
    - ngx_https
  
- name: Enable endpoints
  file:
    src: '/etc/nginx/sites-available/{{ item | regex_replace("\.", "-") }}.conf'
    dest: '/etc/nginx/sites-enabled/{{ item | regex_replace("\.", "-") }}.conf'
    state: link
  with_items: '{{ ngx_endpoints }}'
  notify: 'restart nginx'
  when: ngx_endpoints | length > 0

- name: Start nginx
  systemd:
    name: nginx.service
    state: restarted
    masked: False
    enabled: True

- name: Finale
  debug:
    msg: |
      * NGINX ROLE IS COMPLETED *
