---
- name: Check if dhparams are already generated
  stat:
    path: '/etc/nginx/dhparam.pem'
  register: ngx_stat_dhparam

- name: Generate dhparams
  shell:
    cmd: 'openssl dhparam -out dhparam.pem 2048'
    chdir: '/etc/nginx'
  register: ngx_dhparam
  when: not ngx_stat_dhparam.stat.exists

- name: Verify dhparams
  shell:
    cmd: 'openssl dhparam -inform PEM -in dhparam.pem -check | head -0'
    chdir: '/etc/nginx'
  register: ngx_dhparam_verify
  changed_when: False

- name: Assert that `dhparam.pem` has passed verification
  assert:
    that:
      - ngx_dhparam_verify.stderr == 'DH parameters appear to be ok.'
    success_msg: 'DH parameters verified successfully'
    fail_msg: |
      Failed to verify DH parameters, please investigate:
      {{ ngx_dhparam_verify | to_nice_yaml }}

- name: Generate self-signed cert/key pair for the catch-all server
  shell:
    cmd: |
      openssl ecparam -name prime256v1 > $TMPDIR/ecparam

      openssl req -batch -x509 -nodes -days 3650
      -newkey ec:$TMPDIR/ecparam
      -keyout /etc/nginx/self-signed.key 
      -out /etc/nginx/self-signed.cer

      rm $TMPDIR/ecparam
    creates:
      - '/etc/nginx/self-signed.cer'
      - '/etc/nginx/self-signed.key'

- name: Provision master nginx template
  template:
    src: ngx_nginx_master.j2
    dest: /etc/nginx/nginx.conf
  register: ngx_tpl_master
  notify: 'restart nginx'

- name: There are end-points to work on...
  block:

  - name: Provision endpoints
    template:
      src: ngx_endpoint.j2
      dest: '/etc/nginx/sites-available/{{ item | regex_replace("\.", "-") }}.conf'
    register: ngx_tpl_endpoint
    with_items: '{{ ngx_endpoints }}'

  - name: Create endpoint directories
    file:
      path: '/var/www/html/{{ item | regex_replace("\.", "-") }}'
      state: directory
    with_items: '{{ ngx_endpoints }}'

  when: ngx_endpoints | length > 0
  # << Block end

- name: Provision auxiliary snippets
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  with_items:
    - { src: 'ngx_headers.j2', dest: '/etc/nginx/snippets/headers.conf' }
    - { src: 'ngx_locations.j2', dest: '/etc/nginx/snippets/locations.conf' }
  notify: 'restart nginx'

- name: Remove `snakeoil` certificate
  file:
    path: /etc/nginx/snippets/snakeoil.conf
    state: absent
