---
- name: Add httpasswd file
  community.general.htpasswd:
    path: /etc/nginx/ete_passwords
    name: '{{ esc_http_auth_user }}'
    password: '{{ esc_http_auth_pass }}'
    owner: root
    group: www-data
    mode: 0640

- name: Provision master nginx config
  template:
    src: esc_nginx_master.j2
    dest: /etc/nginx/nginx.conf

- name: Provision EteSync nginx config
  template:
    src: esc_nginx.j2
    dest: /etc/nginx/sites-available/esc_nginx.conf

- name: Enable config
  file:
    src: /etc/nginx/sites-available/esc_nginx.conf
    dest: /etc/nginx/sites-enabled/esc_nginx.conf
    state: link

- name: Restart and enable nginx
  systemd:
    name: nginx.service
    state: restarted
    masked: False
    enabled: True
