---
# Global variables --------------------------------------------------------------------------------

st_install_client: False
st_install_disco: False
st_install_relay: False
st_reinstall: False

# Syncthing client --------------------------------------------------------------------------------

st_client: {
  'addr_use_wan': true,         # Overwrite `st_client.addr` with the discovered WAN ip?
  'addr': '' ,                  # Address on which Client will listen, default: 127.0.0.1
  'port': 8384,                 # Port on which Client's GUI/API will listen, default: 8384
  'announce_broadcast': true,   # Enable "local discovery"?
  'min_free_space': 5,          # Minimum free disk space to keep
  'config_dir': '',             # Will be replaced with $XDG_CONFIG_HOME/syncthing if empty
  'nat': false,                 # Uses upstream-controlled STUN
  'gui': true,
  'gui_tls': true,
  'untrusted': true,            # Set device as "untrusted" by default?
  'recreate_certs': true,       # Re-create certificates? Yields new ID.
  'reconfigure': true,          # Overwrite existing config?

  'user': {
    'name': '',                 # Defaults to SSH user
    'home': '',                 # Will be replaced with $HOME if empty
    },

  'default_folder': {
    'path': '~/sync/default',   # Will be created if does not exist
    'type': 'sendreceive',      # `receiveencrypted` can't be set on the *default* folder
    'pause': True
    },

  'disco': {
    'addr': '127.0.0.1',        # Discovery-server to which Client will connect
    'addr_overwrite': true,     # Overwrite Disco address with the server from this role?
    'port': 8443,               # Port on which Client will try to find Disco, default: 8443
    'id': '',                   # ID of Disco to which Client will connect
    'id_overwrite': true,       # Overwrite `st_client.disco.id` with the `st_disco.id`?
    'enable': true              # Use "global announcements" aka Discovery-server?
    },

  'relay': {
    'enable': true,             # Enable relaying?
    'addr': '',
    'addr_overwrite': true,     # Overwrite Relay address with the server from this role?
    'port': 22067,
    'id': '',
    'id_overwrite': true,       # Overwrite `st_client.relay.id` with the `st_relay.id`?
    'reconnect_interval_minutes': 10
    },

  'start': {                    # Configure autostart via systemd
    'on_boot': true,
    'on_role_completion': 'restarted'   # Either: 'reloaded', 'restarted' or 'stopped'
  },

  'binary': {
    'shasum': '03ba1fb7326d0893fc5664602694144bbdf7717a895fb554fe89fb996f116433',
    'url': 'https://github.com/savchenko/minisync/releases/download/v1.16.2/syncthing',
    }
}

# Discovery-server --------------------------------------------------------------------------------

st_disco: {
  'addr': '127.0.0.1',         # Address on which Disco listens itself
  'addr_use_wan': true,        # Use discovered WAN IP instead of the provided address?
  'port': 8443,                # Port on which Disco will listen itself, default: 8443
  'id': '',                    # Disco's own ID, *will* be overwritten during run
  'recreate_certs': true,      # Re-create certificates? Yields new ID.
  'replicate': false,          # Add `st_disco_replica` into the systemd config?

  'replica': {
    'addr': '10.0.0.1',        # Address which Disco will use for replication
    'port': 19200,             # Port which Disco will use for replication
    'id': '',                  # ID of another replica instance
    'listen_addr': '10.0.0.2', # Address for incoming replication connections
    'listen_port': 19200,      # Port for incoming replication connections, default: 19200
    },

  'start': {                   # Configure autostart via systemd
    'on_boot': true,
    'on_role_completion': 'restarted'   # Either: 'reloaded', 'restarted' or 'stopped'
  },

  'binary': {
    'shasum': '6988838343dbf98eacb6678d551ae298fa85c1c0a4b0e2b2cff62e7228c442aa',
    'url': 'https://github.com/savchenko/minisync/releases/download/v1.16.2/stdiscosrv',
    }
}

# Relay -------------------------------------------------------------------------------------------

st_relay: {
  'addr': '',
  'addr_use_wan': true,
  'port': 22067,
  'network_timeout_string': '2m0s',
  'ping_interval_string': '1m0s',
  'recreate_certs': true,

  'nat': {
    'enabled': false,          # Use UPnP/NAT-PMP to acquire external port mapping?
    'lease_minutes': 60,
    'renewal_minutes': 30,
    'timeout_seconds': 10
  },

  'start': {                   # Configure autostart via systemd
    'on_boot': true,
    'on_role_completion': 'restarted'   # Either: 'reloaded', 'restarted' or 'stopped'
  },

  'binary': {
    'shasum': '715525cb0e835153a1ff465f312009c2ffc4d5d28294d850018087ee5727d238',
    'url': 'https://github.com/savchenko/minisync/releases/download/v1.16.2/strelaysrv'
  }
}
