---
- name: (Block) Update local SSH authorized keys
  block:

    - name: Remove cached keys which are outdated by now
      shell:
        cmd: >
          ssh-keygen -R {{ item }}
          -f "{{ lookup("env", "HOME") }}/.ssh/known_hosts"
      register: ssh_keygen_remove
      with_items:
        - '{{ hostvars[inventory_hostname]["ansible_host"] }}'
        - '{{ inventory_hostname }}'
      when: item != 'localhost'
      loop_control:
        label: |-
          {{ item | default("...") }} =>
          {{ ssh_keygen_remove.stdout | default("...") }}
      # Retries are warranted as Ansible can't always cope with the modern NVMEs
      retries: 3
      delay: 2

    - name: Login into each host to save their SSH fingerprints
      shell:
        cmd: >
          ssh
          {{ hostvars[inventory_hostname]["ansible_user"] }}@{{ item }}
          "hostname; exit"
      with_items:
        - '{{ hostvars[inventory_hostname]["ansible_host"] }}'
        - '{{ inventory_hostname }}'
      when: item != 'localhost'
      loop_control:
        label: '{{ item | default("...") }}'
      retries: 3
      delay: 2

  delegate_to: localhost
  become: True
  become_user: '{{ lookup("env", "USER") }}'
