---
- name: restart sshd
  service:
    name: sshd
    state: restarted
  become: True
  become_user: root
  listen: 'restart sshd'

- name: restart ufw
  service:
    name: ufw
    state: restarted
  become: True
  become_user: root
  listen: 'restart ufw'

- name: restart rsyncd
  service:
    name: rsync
    state: restarted
  become: True
  become_user: root
  listen: 'restart rsyncd'

- name: reload sysctl
  shell: sysctl --system
  become: True
  become_user: root
  listen: 'reload sysctl'

- name: restart timesyncd
  service:
    name: systemd-timesyncd
    state: restarted
  become: True
  become_user: root
  listen: 'restart timesyncd'

- name: Reconfigure SSHd
  shell:
    cmd: dpkg-reconfigure -f noninteractive openssh-server
  become: True
  become_user: root
  listen: 'reconfigure sshd'

- name: reconfigure keyboard settings
  shell: dpkg-reconfigure -f noninteractive keyboard-configuration
  become: True
  become_user: root
  listen: 'dpkg_keyboard'

- name: restart sshguard
  service:
    name: sshguard
    state: restarted
  become: True
  become_user: root
  listen: 'restart sshguard'

- name: Restart Knot
  service:
    name: kresd@1
    state: restarted
  become: True
  become_user: root
  listen: 'restart kresd'

- name: Restart thermald
  service:
    name: thermald
    state: restarted
  become: True
  become_user: root
  listen: 'restart thermald'

- name: Restart unattended-upgrades
  service:
    name: unattended-upgrades
    state: restarted
  become: True
  become_user: root
  listen: 'restart unattended-upgrades'

- name: Update GRUB
  command: grub-mkconfig -o /boot/grub/grub.cfg && update-grub
  listen: 'grub_update'
  become: True
  become_user: root
  notify: reboot host

- name: Rotate logs
  command: 'logrotate -f /etc/logrotate.conf'
  become: True
  become_user: root
  listen: 'rotate logs'

- name: Reload systemd
  systemd:
    daemon_reexec: True
    daemon_reload: True
  become: True
  become_user: root
  listen: 'reload systemd'

- name: Reboot target host
  reboot:
    msg: 'Rebooting {{ ansible_hostname | upper }} @ {{ ansible_host }}'
    # Safety!
    connect_timeout: 2
    post_reboot_delay: 1
  become: True
  become_user: root
  when: ansible_connection != "local" and base_allow_reboot
  listen: 'reboot host'

- name: Reload udev rules
  shell: udevadm control --reload-rules
  become: True
  become_user: root
  listen: 'reload udev'
