---
- name: Preflight checks
  import_tasks: u2d_preflight.yml
  become: True
  become_user: root
  tags:
    - u2d_preflight

- name: Cleanup Ubuntu installation
  import_tasks: u2d_cleanup_pre.yml
  become: True
  become_user: root
  tags:
    - u2d_cleanup_pre

- name: Crossgrade system to Debian 11
  import_tasks: u2d_crossgrade.yml
  become: True
  become_user: root
  tags:
    - u2d_crossgrade

- name: Straighten the resulting hybrid
  import_tasks: u2d_cleanup_post.yml
  become: True
  become_user: root
  tags:
    - u2d_cleanup_post
