---
- name: Register existing permissions overrides
  shell:
    cmd: 'dpkg-statoverride --list | cut -d " " -f 4'
  register: dpkg_existing_overrides
  changed_when: False
  failed_when: dpkg_existing_overrides.stdout_lines | length < 2
  become: True
  become_user: root

- name: (1/1) Transform existing overrides into the digestible form...
  set_fact:
    dpkg_existing_overrides: '{{ dpkg_existing_overrides.stdout_lines }}'

- name: Register new permissions overrides
  read_csv:
    # read_csv doesn't accept relative path for some reason
    path: '{{ role_path }}/files/conf/dpkg_overrides.csv'
    delimiter: ','
    strict: True
  register: dpkg_overrides
  delegate_to: localhost
  become: True
  become_user: '{{ lookup("env", "USER") }}'

- name: (1/2) Transform new overrides into the digestible form...
  set_fact:
    dpkg_overrides: '{{ dpkg_overrides | dict2items }}'

- name: (2/2) Transform new overrides into the digestible form...
  set_fact:
    dpkg_overrides: '{{ dpkg_overrides[1].value }}'

- name: Update permissions overrides
  shell:
    cmd: '{{ "dpkg-statoverride --update --add " + item["user"] + " " + item["group"] + " " + item["chmod"] + " " + item["path"] }}'
  become: True
  become_user: root
  with_items: '{{ dpkg_overrides }}'
  loop_control:
    label: >
      {{ item.user | default("") }}:{{ item.group | default("") }}
      {{ item.chmod | default("") }} {{ item.path | default("") }}
  when: item['path'] not in dpkg_existing_overrides
